<?xml version="1.0" encoding="UTF-8"?>
<definitions name="CommonPolicies" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://ally.com/policies/common/v1/"
  targetNamespace="http://ally.com/policies/common/v1/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy">
  <documentation>This policy file contains policies that are applicable across all services. Version 1.0</documentation>

  <wsp:Policy wsu:Id="UsernameToken-Plain" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
    xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
    <sp:SupportingTokens>
      <wsp:Policy>
        <sp:UsernameToken sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
          <wsp:Policy>
            <sp:WssUsernameToken10 />
          </wsp:Policy>
        </sp:UsernameToken>
      </wsp:Policy>
    </sp:SupportingTokens>
  </wsp:Policy>
</definitions>